### PR TITLE
- Make mock structs for testify.go public

### PR DESCRIPTION
**Pull request by jomaresch**

### CODE REVIEW

**Review by roubanakhle — APPROVED** [review]

**Comment by felix-kaestner** [comment]
Why do you need those to be public? You can construct new instances with the generated `NewX` method and should probably never want to use the real type of the mock structs but rather use the interface type they implement. 🤔

**Comment by jomaresch** [comment]
Jo, the issue is, that we have some huge test which depend on these mocks. 
For each subtest we have to create a new mocks, which cause a lot of boiler code. 
It would be nice to store an instance of the mock to reuse it for the subtest.
This is not possible atm. 
I'm open for suggestions

**Comment by felix-kaestner** [comment]
> Jo, the issue is, that we have some huge test which depend on these mocks. For each subtest we have to create new mocks, which cause a lot of boiler code. It would be nice to store an instance of the mock to reuse it for the subtest. This is not possible atm. I'm open for suggestions

Couldn't you just define a variable like `mock := NewFoo()` and then reuse this variable in multiple subtests? 🤔 Maybe a short code example would help me to understand the issue here.

But either way, this instance should probably be defined with the interface type and not with the concrete type of the mock struct.

I'm also not against these changes, I'm just trying to understand why they are necessary, since the struct type has been made private for the reason that it should never be needed.

**Comment by jomaresch** [comment]
e.g. a testify suite 
https://pkg.go.dev/github.com/stretchr/testify/suite
```
type ExampleTestSuite struct {
    suite.Suite
    mock *mockFooClient // Not possible because the mock is private
    mock  FooClient // Possible, but now I can't use suite.mock.OnSayHello() later
}

func (suite *ExampleTestSuite) SetupTest() {
    suite.mock = NewMockFooClient()
}

func (suite *ExampleTestSuite) TestExample() {
    suite.mock.OnSayHello()...
}
```

The default client interface only has the `SayHello` func but not the `OnSayHello` func.

Also some linters don't like this:
https://www.reddit.com/r/golang/comments/xurmnl/return_unexported_type/

**Comment by felix-kaestner** [comment]
> e.g. a testify suite https://pkg.go.dev/github.com/stretchr/testify/suite
> 
> ```
> type ExampleTestSuite struct {
>     suite.Suite
>     mock *mockFooClient // Not possible because the mock is private
>     mock  FooClient // Possible, but now I can't use suite.mock.OnSayHello() later
> }
> 
> func (suite *ExampleTestSuite) SetupTest() {
>     suite.mock = NewMockFooClient()
> }
> 
> func (suite *ExampleTestSuite) TestExample() {
>     suite.mock.OnSayHello()...
> }
> ```
> 
> The default client interface only has the `SayHello` func but not the `OnSayHello` func.
> 
> Also some linters don't like this: https://www.reddit.com/r/golang/comments/xurmnl/return_unexported_type/
> 
> I could also run this in every test, but we try to avoid this.
> 
> ```
> mock := NewMockFooClient() 
> ```
> 
> Also , this PR is no urgent, just something I would like to discuss 😀

Okay, I see why having an exported type would be needed in that example. I think in general, it's not always a good practice to introduce such abstractions for testing, since test code should be kept simply and easy to follow (see e.g. [this blog post](https://testing.googleblog.com/2019/12/testing-on-toilet-tests-too-dry-make.html)). So in that sense I'd say constructing new instances in each test (with `NewMockFooClient`) should be preferred even despite of the repetition.

That being said, I'm also fine with exporting the struct type since that basically matches what other projects like https://github.com/uber-go/mock do and what is generated for `pegomock`: https://github.com/lovoo/protoc-gen-go-grpcmock/blob/e44c38fe7354d1284e685a9d2218b2612cd02548/examples/helloworld/pegomock/helloworld_grpc_mock.pb.go#L22

So feel free go go ahead with this PR. 😄

**Review by frairon — APPROVED** [review]

**Pull request merged**
